### ISSUE TITLE
Online Documentation

### ISSUE THREAD

**Issue by Edenhofer** [davidogara/hetGPy#10]
It would be great if the documentation would be hosted online and linked to in the README.

Part of https://github.com/openjournals/joss-reviews/issues/7518 .

**Comment by Edenhofer** [comment]
Awesome! Thank you for fixing this so quickly.

While scrolling through the documentation, I noticed that the lower entries at https://hetgpy.readthedocs.io/en/latest/reference.html#hetgpy.hetGP.hetGP.mleHetGP have some malformed strings in them. Your changes fully addressed my issue but it might be worth cleaning up those formatting issues too while at it.

**Comment by davidogara** [comment]
Thanks for pointing this out-- I took a pass at fixing the malformed strings, and the updated documentation is available at: https://hetgpy.readthedocs.io/en/latest/reference.html#hetgpy.hetGP.hetGP.mleHetGP

**Comment by Edenhofer** [comment]
Perfect! Thanks!
