### ISSUE TITLE
Analysis Script for the paper

### ISSUE THREAD

**Issue by davidogara** [davidogara/hetGPy#13]
From @Edenhofer, part of https://github.com/openjournals/joss-reviews/issues/7518

Could you provide a script to reproduce the performance timings from the paper?

**Comment by davidogara** [comment]
Our analysis scripts to generate the results in the paper is found at:

https://github.com/davidogara/hetGPy/tree/main/paper/analysis

**Comment by Edenhofer** [comment]
:+1: Thank you! :)

**Comment by davidogara** [comment]
@Edenhofer just checking in to see if you had any feedback on the analysis script, or if not, if you wouldn't mind closing this issue. Happy to address any follow-up if you have it!

**Comment by Edenhofer** [comment]
I'm happy with the script. Feel free to close the issue. As I didn't open the issue, I'm unable to close it myself.
