### ISSUE TITLE
Tests Without Comparisons

### ISSUE THREAD

**Issue by DanWaxman** [davidogara/hetGPy#18]
Some tests run the R code and hetGPy code, but never actually compare the results as far as I can tell.

For example, in `tests/test_optim_and_update/test_update_homGP.py`, there *is* such a check:
https://github.com/davidogara/hetGPy/blob/8de1a04a78765014dca0021731fcf32ede8a19f1/tests/test_optim_and_update/test_update_homGP.py#L62
but in the corresponding test case for `hetGP`, there is no assertion statement:
https://github.com/davidogara/hetGPy/blob/8de1a04a78765014dca0021731fcf32ede8a19f1/tests/test_optim_and_update/test_update_hetGP.py#L8-L62

This seems to be a common problem in the `test_optim_and_update` folder. For example, 
https://github.com/davidogara/hetGPy/blob/8de1a04a78765014dca0021731fcf32ede8a19f1/tests/test_optim_and_update/test_IMSPE_optim.py#L8-L53
also does not have a test.

Looking briefly, this does not seem to be an issue in the `tests` folder. 

Part of https://github.com/openjournals/joss-reviews/issues/7518

**Comment by davidogara** [comment]
Thanks for bringing this up @DanWaxman -- I think that these are residual from an earlier version of the library where the sequential routines (so the `update` methods and any of the acquisition functions) had bugs when you tried to run them end-to-end, but these have been resolved now.

I think a more appropriate test would be to consolidate these tests into one that confirms that the sequential function acquisitions from `homGP` (in R) and `homGP` (in hetgpy) for a simple example are the same.

I added the test:
https://github.com/davidogara/hetGPy/blob/main/tests/test_optim_and_update/test_sequential_EI.py

Which passes. Given that more complicated examples might be more tricky to test, I'd be inclined to have this test included in the testing suite and remove `test_IMSPE_optim`, `test_crit_optim`, `test_update_hetGP`, and `test_update_homGP` 

If you think that is appropriate, let me know. Thanks again for the careful review

**Comment by DanWaxman** [comment]
I think there's probably value in keeping these "trickier" tests -- e.g., if they were useful to help identify and resolve old bugs in `update` methods, they may well prove useful in catching some potential future bugs. But I don't view this as critical, the proposed `test_sequential_EI.py` should be sufficient; I just think broader coverage rarely hurts. Thanks again for being so receptive and timely in your replies.

**Comment by davidogara** [comment]
That makes sense-- I was able to simply the tests a bit (the results are far more stable when we only do a single update step in the acquisition functions) and compare the results between hetGP and hetgpy (and they pass)

For a future version of the library I think it would make sense to have a longer worked example test that does more update steps (say like 5 or even 10) that shows that hetGP (from R) and hetgpy stay in synch

**Comment by DanWaxman** [comment]
Thanks! 

> For a future version of the library I think it would make sense to have a longer worked example test that does more update steps (say like 5 or even 10) that shows that hetGP (from R) and hetgpy stay in synch

Perhaps it makes sense to create a separate GH issue for this in case a future contributor to the library decides to take this on. But I'll close this issue for now.
