### ISSUE TITLE
Documentation and Potential Typing

### ISSUE THREAD

**Issue by DanWaxman** [davidogara/hetGPy#20]
I think the last remaining aspect of my review is documentation, with some further documentation in order in some places. In particular, some functions which are documented in `hetGP`are not documented in `homGP`, e.g. `logLikHom`: https://github.com/davidogara/hetGPy/blob/8456992bad244d2ece4720e9eba93807b7812086/hetgpy/homGP.py#L31

I understand some methods are not API level, but e.g., `predict` and `update` should be, and are not documented. In my opinion, full documentation is necessary in cases like this to satisfy the "Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?" part of the checklist. 

While I do not find type hints entirely necessary, I believe it would be a big plus. A pure `numpy` solution would be using [`numpy.typing`](https://numpy.org/doc/stable/reference/typing.html). Even better would be [`jaxtyping`](https://github.com/patrick-kidger/jaxtyping), which contrary to the name is fully compatible with regular `numpy`, and allows for array shapes and static type checking.

Part of https://github.com/openjournals/joss-reviews/issues/7518

**Comment by davidogara** [comment]
@DanWaxman thanks for the suggestion, I think these would be very helpful too.

I'll take a pass at updating the log-likelihood, predict, and update methods, as well as adding type hints to those (and the MLE methods)

**Comment by davidogara** [comment]
@DanWaxman just updating this thread to let you know I added documentation and type hints to the likelihoods, gradient, MLE, update, and predict methods. Please feel free to take a look and let me know what you think!

**Comment by DanWaxman** [comment]
Thanks, these look great!
