### ISSUE TITLE
Deployment Failing

### ISSUE THREAD

**Issue by DanWaxman** [davidogara/hetGPy#21]
As a final point to https://github.com/openjournals/joss-reviews/issues/7518, the deployments to PyPi are failing. The logs are expired, so I am not sure why (the warnings look innocuous) -- but this should be resolved.

**Comment by davidogara** [comment]
Thanks @DanWaxman -- I had some issues with the deployment previously, but I will take a look today and see if I can fix it.

**Comment by davidogara** [comment]
@DanWaxman I believe I have addressed this. There were some old environments I had to delete, but the workflow successfully pushed hetgpy v1.0 to pypi

Can you take a look and let me know what you think?

**Comment by DanWaxman** [comment]
Looks good to me! I confirmed in a Colab notebook that I can install `hetgpy-1.0.0` and run the motorcycle example.
